### ISSUE TITLE
Changing boolean type from int to bool

### ISSUE THREAD

**Issue by ijacquez** [iZarif/tsra#3]
I noticed a commit, changing certain return types from `long` to `int`.

`int` is also used as a boolean instead of `bool`. Maybe this should be changed to make it clear what the return value is meant to be. This causes issues with < C99 compatibility, but this could be mitigated.

```
TS_EXPORT int ts_is_str(ts_ptr p);
TS_EXPORT int ts_is_num(ts_ptr p);
TS_EXPORT int ts_is_int(ts_ptr p);
TS_EXPORT int ts_is_real(ts_ptr p);
TS_EXPORT int ts_is_char(ts_ptr p);
TS_EXPORT int ts_char_val(ts_ptr p);
TS_EXPORT int ts_is_vec(ts_ptr p);
```

There's a few more with the `*_is_*(..)` pattern, but you get the idea.

There are also, I believe a few that use `char` as well.

What do you think?

**Comment by iZarif** [comment]
> Maybe this should be changed to make it clear what the return value is meant to be.

That's a good idea.

**Comment by ijacquez** [comment]
Thank you for the commit.
